spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/volunteer_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Secret and Expiration (Dummy values for prototype)
app.jwt.secret=94a08da1fecbb6e8b46990538c7b50b2a75d5a9db48347895e6f54c9c2b4c10c
app.jwt.expiration-ms=86400000

# API configuration
server.port=8081
server.servlet.context-path=
